### ISSUE TITLE
(OpenComputers) Return wrong values

### ISSUE THREAD

**Issue by P3ridot** [ZeroNoRyouki/BigReactors-OLD#206]
Hi, I find a bug consisting of reactor.getHotFluidAmount() return amout of coolant and reactor.getCoolantAmount() return amount of hot fluid :v

**Comment by ZeroNoRyouki** [comment]
In which version? I've just checked the last 1.12.2 one and it look correct to me

**Comment by McKoxu** [comment]
ExtremeReactors 1.12.2 0.4.5.67

**Comment by ZeroNoRyouki** [comment]
It's correct then. getCoolantAmount() is asking the reactor the amount of the cold fluid, and getHotFluidAmount() the hot one. On what base do you feel that there is an error somewhere?

**Comment by McKoxu** [comment]
Video how it looks: https://youtu.be/im2lqbddlm4

And code: https://pastebin.com/RDWtgqjy

**Comment by McKoxu** [comment]
If I'll put reactor.getHotFluidAmount() instead reactor.getCoolantAmount() I get amount of Water ;v

**Comment by ZeroNoRyouki** [comment]
Could you test it without the OC Adapter block? You don't need one to talk to the Computer Port

**Comment by McKoxu** [comment]
Without Adapter nothing has been changed :/
